### PR TITLE
Add links to download data as csv

### PR DESCRIPTION
**Pull request by mlolson**

### CODE REVIEW

**Comment by jcollum** [comment]
`mo-data`? as in mo' data? Just curious.

**Comment by mlolson** [comment]
Its my initials. Just a way of name spacing branches.

**Comment by mostlycarbonite** [comment]
I'm taking your word for it. Chemo day here so I am out of brain cells. All good.

**Comment by mlolson** [comment]
@mostlycarbonite Damn dude sorry to hear that. That sounds completely shitty. Hope you make a full recovery. If you need me to do anything on the site just shoot me an email.

**Pull request merged**
